### ISSUE TITLE
Custom config parameter being ignored?

### ISSUE THREAD

**Issue by byrnereese** [articulate/actions-markdownlint#11] opened 2023-06-24 08:19 UTC
I am in the process of deploying this to my company's documentation repository. However, the config file I would like to use appears to be ignored. 
https://github.com/ringcentral/ringcentral-api-docs/actions/runs/5363287621/jobs/9730747097

I did notice that the Docker file copies over the static config file:
https://github.com/articulate/actions-markdownlint/blob/db8d711e63896910f9684fbf4474c8ac0862f685/Dockerfile#L3

Is this right? Should it not copy over my personal config?

**Comment by mloberg** [comment] 2023-06-30 14:34
I can't see the linked run and I'm not able to reproduce locally.

The Docker action type builds the container and then runs it. So the original copy is the default config we use. Then when it runs, it will either use the `config` input or attempt to find a [config file](https://github.com/articulate/actions-markdownlint/blob/db8d711e63896910f9684fbf4474c8ac0862f685/entrypoint.sh#L20) at the root.

Without seeing how this was produced, I'm unable to debug any further

**Comment by mloberg** [comment] 2023-07-21 14:02
Going to close this. If you are able to reproduce this, please re-open and we can take a look at it

**Closed by mloberg** 2023-07-21 14:02 UTC
